
version: '3.8'

services:

  postgresDB:
    image: postgres:15-alpine
    container_name: postgres_relatorio_to
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: relatorio_to
    ports:
      - "5432:5432"
    networks:
      - relatorio-network


  api-gerador:
    build: .
    container_name: api_gerador_relatorio_to
    ports:
      - "8080:8080"
    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/relatorio_to
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgresDB
    networks:
      - relatorio-network


networks:
  relatorio-network:
    driver: bridge