spring.application.name=gerador_relatorio_to
​spring.datasource.url=jdbc:postgresql://localhost:5432/relatorio_to
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=CHAVE_FALSA_POR_ENQUANTO
